### ISSUE TITLE
Does not work with Realm 5.8.0

### ISSUE THREAD

**Issue by ghost** [vicpinm/Kotlin-Realm-Extensions#62]
Upon lowering the version to Realm 5.7.0 the code works fine but when I update the version to 5.8.0, and try to save a realm object, it gives me the following exception

<pre> Caused by: java.lang.NoSuchMethodError: No virtual method copyToRealm(Lio/realm/RealmModel;)Lio/realm/RealmModel; in class Lio/realm/Realm; or its super classes (declaration of 'io.realm.Realm' appears in /data/app/com.allective-KIOgR_c-RriD_qNKZ3EWpQ==/split_lib_dependencies_apk.apk)
        at com.vicpin.krealmextensions.RealmExtensionsKt$save$1.invoke(RealmExtensions.kt:266)
        at com.vicpin.krealmextensions.RealmExtensionsKt$save$1.invoke(Unknown Source:2)
        at com.vicpin.krealmextensions.RealmExtensionsKt$transaction$$inlined$use$lambda$1.execute(RealmExtensions.kt:198)
        at io.realm.Realm.executeTransaction(Realm.java:1493)
        at com.vicpin.krealmextensions.RealmExtensionsKt.transaction(RealmExtensions.kt:198)
        at com.vicpin.krealmextensions.RealmExtensionsKt.save(RealmExtensions.kt:262)
        at com.allective.api.ApiImplementation$getLogin$1.accept(ApiImplementation.kt:39)
        at com.allective.api.ApiImplementation$getLogin$1.accept(ApiImplementation.kt:18)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6798) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) </pre>

**Comment by vicpinm** [comment]
Hi, I'll try to take a look to this soon. Currently, library supports Realm up to 5.7.0 only.

**Comment by vicpinm** [comment]
Hi  @rohitgupta-kiwi , version compile "com.github.vicpinm:krealmextensions:2.4.0" is now available with support for realm 5.8.0.
